### ISSUE TITLE
config_dir

### ISSUE THREAD

**Issue by Faryshta** [feulf/RainDB#1]
I think the `config_dir` should not be part of the `DB::$conf` array.

The `config_dir` is meant to be know when executing the `DB::init` method and it won't be used again. So having that information on the `DB::$conf` will be useless.

Currently the way to change the `config_dir` is by

``` php
DB::configure('new_dir/');
DB::init('prod');
```

A way I propose to solve this is by

``` php
    public static function configure($name = null, $dir = 'config/')
    {
          // method body
    }
```

This way the usage will be

``` php
DB::init('prod', 'new_dir/');
```

**Comment by feulf** [comment]
DB::Configure() is meant to be called just once, as the self::$conf is a
static variable each setting should be configured before the init(). The
idea of having config_dir, config_file and all the other configuration
there is to make a common interface to setup the class, which is the same
as the RainTPL, and next to RainForm and to the other components. Another
advantage to have that kind of configuration is to make a simple
documentation page for DB::configure() with the list of all the options
configurable.

Does it make sense to you?
